timeout: 3
default_entry: "AstraOS"

entry "AstraOS" {
    protocol: limine

    kernel_path: "/boot/kernel.elf"
    module_path: "/boot/initrd.img"

    framebuffer {
        width: 1920
        height: 1080
        bpp: 32
        memory_model: rgb
        request: yes
    }
}

entry "TextFallback" {
    protocol: limine
    kernel_path: "/boot/kernel.elf"
    graphics: text
}
